model_config:
  model_name: nninteractive_v1
  model_version: v1
  device: null
  sync_device: true
  use_memory: true
  download_dir: null

prompt_generation:
  seed: 42

  prompt_generation_config:
    surface_band_mask_iter: 0 
    neg_mask_dilation_iter: 3

    num_pts_pos: 1
    num_pts_neg: 1
    num_slices_pts: 1
    alpha_sampling_pts: 1.0

    num_bbox_pos: 0
    num_slices_bbox: 1

    scribble_diameter_ann: false
    num_slices_scribble_diameter_ann: 1

    scribble_spline: false
    num_slices_scribble_spline: 1
    num_scribble_spline: 1
    num_control_points_scribble_spline: 3

    noise:
      point_jitter_std: 0.0
      bbox_jitter_std: 0.0

  crop_roi_config:
    enable: false
    margin_mode: absolute
    margin: 5
    fraction: 0.3333
    min_margin: 5
    max_margin: 64
