import numpy as np

from utils.helpers.sample_slices import sample_slices_from_mask

def generate_bbox_prompts(
    pos_mask: np.ndarray, 
    num_bboxes: int = 1, 
    num_slices: int = 1,
    rng: np.random.Generator | None = None
) -> tuple[tuple[float, float, float, float, float, float], ...]:
    """
    Generate 2D positive bounding box prompts from a 3D mask.

    Bounding boxes are generated by first sampling slices from the foreground extent of the mask with a bias towards the center, and then computing the bounding box coordinates of the positive pixels in each selected slice. The bounding box coordinates are formatted as (x_min, x_max), (y_min, y_max), (z, z+1) to represent a thin bounding box in the axial direction.

    Args:
        pos_mask: Binary 3D mask of shape (H, W, D) where foreground voxels are represented by True (or 1) and
            background voxels by False (or 0).
        num_bboxes: Number of bounding boxes to generate.
        num_slices: Number of axial slices to sample from the foreground extent of the mask.
        rng: NumPy random number generator.

    Returns:
        A tuple of bounding box coordinates in the format ((x_min, x_max), (y_min, y_max), (z, z+1)).

    Raises:
        ValueError: If the positive mask is not a NumPy array.
        ValueError: If the positive mask is not 3-dimensional.
        ValueError: If the positive mask is not binary.
        ValueError: If the number of bounding boxes to generate is not positive.
        ValueError: If the positive mask contains no foreground voxels.
    """
    # Input mask validation
    if not isinstance(pos_mask, np.ndarray):
        raise ValueError("Positive mask must be a numpy array.")
    if pos_mask.ndim != 3:
        raise ValueError("Positive mask must be a 3D array.")
    if not pos_mask.dtype == bool:
        raise ValueError("Positive mask must be binary (values 0/1 or bool).")
    if not np.any(pos_mask):
        raise ValueError("Positive mask contains no foreground voxels to generate prompts from.")

    # Parameters validation
    if num_bboxes <= 0:
        raise ValueError("Number of bounding boxes to generate must be greater than zero.")
    if num_slices <= 0:
        raise ValueError("Number of slices to sample must be greater than zero.")

    # Create a random generator if not provided
    if rng is None:
        rng = np.random.default_rng()

    # Sample slices from the foreground extent of the mask with a bias towards the center
    sampled_slices_idx = sample_slices_from_mask(
        pos_mask, 
        num_slices=num_slices, 
        axis=2, # Sample slices along the axial direction
        center_bias=2.0,
        rng=rng
    )

    # For each selected slice, compute the bounding box coordinates of the positive pixels in that slice and add them to the list of sampled bounding boxes
    sampled_bboxes = []
    for slice_idx in sampled_slices_idx:
        slice_mask = pos_mask[:, :, slice_idx]  
        if np.any(slice_mask):
            # Get the coordinates of the positive pixels in the slice
            coords = np.argwhere(slice_mask)
            x_min, y_min = coords.min(axis=0)
            x_max, y_max = coords.max(axis=0)

            # Format for the 2D bounding box coordinates: (x_min, x_max), (y_min, y_max), (z, z+1) to represent a thin bounding box in the axial direction
            sampled_bboxes.append(((int(x_min), int(x_max)), (int(y_min), int(y_max)), (slice_idx, slice_idx + 1)))

    return tuple(sampled_bboxes)
